CLOUDINARY_URL: "cloudinary://448455548215922:Riqe5mc9jYlS6P2__lw1Wl4vliM@guidocld"

ALGOLIA_APPLICATION_ID: "MP37CKD4Q3"
ALGOLIA_API_KEY: "428ddbfabd7516b4675a599ffd9ea4c8"
ALGOLIA_SEARCH_ONLY_API_KEY: "136ef84efd2cef33f59cda19d45384db"

GOOGLE_API_SERVER_KEY: "AIzaSyCGT5QUMqptyIbrUxUuVBizlj6rPaC0qXI"

GOOGLE_API_BROWSER_KEY: "AIzaSyCH0sbuaIoH7zlsrufIdtx2pclD-_MmUXk"
